name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  unit_tests:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
    - name: Unit tests
      run: go test -v ./...
